[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'yonchu/accelerated-smooth-scroll'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'cocopon/vaffle.vim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
